# Configuration file for bundler-age_gate
# Place this file in your project root

# Global minimum age in days (default for all sources)
minimum_age_days: 7

# Path to audit log file (default: .bundler-age-gate.log)
audit_log_path: .bundler-age-gate.log

# Gem sources configuration
# Define multiple sources with different age requirements
sources:
  # Public RubyGems (default)
  - name: rubygems
    url: https://rubygems.org
    api_endpoint: https://rubygems.org/api/v1/versions/%s.json
    minimum_age_days: 7  # Stricter for public gems

  # GitHub Packages (private gems)
  - name: github-internal
    url: https://rubygems.pkg.github.com/your-org
    api_endpoint: https://rubygems.pkg.github.com/your-org/api/v1/versions/%s.json
    minimum_age_days: 3  # Less strict for internal packages
    auth_token: ${GITHUB_TOKEN}  # Environment variable substitution

  # Internal Artifactory
  - name: artifactory
    url: https://artifactory.company.com/api/gems
    api_endpoint: https://artifactory.company.com/api/gems/api/v1/versions/%s.json
    minimum_age_days: 1  # Very permissive for internal gems
    auth_token: ${ARTIFACTORY_API_KEY}

# Exceptions for approved gems
exceptions:
  # Example: Critical security fix
  - gem: rails
    version: 7.1.3.1
    reason: "Critical security patch for CVE-2024-12345"
    approved_by: security-team
    expires: 2026-02-15

  # Example: Internal gem (all versions)
  - gem: company-shared-utils
    reason: "Internal gem under our control"
    approved_by: platform-team

  # Example: Time-limited exception
  - gem: new-monitoring-tool
    version: 2.0.0
    reason: "Required for incident response, approved by CTO"
    approved_by: cto
    expires: 2026-01-30
